name: dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  supabase: ^2.2.5
  http: ^1.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
