name: taxi-app
description: 'A taxi-app built with Flutter and Supabase.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.9
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  duration: ^3.0.13
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
